// Listes des élèves par classe (clé = niveau + numéro, ex. "61" pour la 6e1).
// Utilisées pour proposer automatiquement les vendeurs dans le bon de commande.
const ELEVES = {
    "31": [ // 3e1
        "ADEP ABOUYA Loubna",
        "ARROSSA Eztitxu",
        "BERETERBIDE Amane",
        "BOUCHARD Valentina",
        "CASET Chloé",
        "CERATO ETCHEVERRIA Mathis",
        "DAGORRET Unai",
        "DOS SANTOS Maïna",
        "DUHART Clara",
        "DYIAN SAENZ Lena",
        "EIZAGUIRRE Laida",
        "GARATEIX Bettina",
        "HARRIET Lutxi",
        "INDA Emma",
        "IVACHEFF Alaia",
        "JAUREGUY Kayla",
        "LARRANDE Leire",
        "LATASA Lenny",
        "LESAGE Djoyce",
        "MINONDO JÉGOUIC Eneko",
        "MOGABURE Julen",
        "MOUTROUSTEGUY Anaiz",
        "OIARTZUN NÍ SHÍOCHÁIN Banba",
        "OLAZAR IRIGOYEN Jone",
        "PALOMES Iban",
        "SADIO KAMARA Malick",
        "SALDUBEHERE Laura",
    ],
    "61": [ // 6e1
        "ANDRES Elaia",
        "BELASRI Marwa",
        "BONNETERRE Lucie",
        "BOUKREDIA Ilias",
        "CANTAU Xabi",
        "CHRISTY Anna",
        "DESTRIBATS Esteban",
        "ERGUY Nahia",
        "ETCHAMENDY Nahia",
        "FUMERY Lise",
        "GARCIA ALBIERO Ethan",
        "GEYS Eneko",
        "GUEDMA MATTIVI Neyla",
        "HARANGER Eneko",
        "HUBERT Charline",
        "JAUREGUY Amets",
        "LABOURDIQUE Célia",
        "LAGARDE Amaia",
        "LAHETJUZAN Eneko",
        "LARZABAL Lorea",
        "MICHOT Sarah",
        "MIRANDE Jade",
        "PALÉ RECHIK Lola",
        "VALDES Zoé",
        "WRIGHT Louise",
    ],
    "62": [ // 6e2
        "AMORENA Pablo",
        "BONNEFON Lea",
        "BORDES Taïna",
        "BRIERE Eva",
        "CADELO MONNIN Mila",
        "COELHO Eneko",
        "DUBLANC Xan",
        "ETCHART Chloé",
        "ETCHEPARE Antton",
        "ETCHEVERRY Charlie",
        "EYHERAMOUNHO Andoni",
        "FERREIRA CONDON Andréa",
        "FLORES Thomas",
        "GANJAYEVA Banu",
        "HODET Louka",
        "HOUILLON Alicia",
        "JANICKI Louis",
        "JOCOU LARRE Extebe",
        "LAGARDE Antton",
        "MARSAN Adèle",
        "MAZAIN Luka",
        "RAGUE Eneko",
        "RALITAVAO RAKOTAVA ZAHA Alexis",
        "SIMOES DENOUAL Angèle",
        "TARTARIN Camille",
        "TINTINGER Amaia",
        "URCHUEGUIA Milan",
        "VIDON Eden",
        "VILARO Jade",
    ],
    "63": [ // 6e3
        "ALLEZY Ludwig",
        "ARRIETA Victoire",
        "AYENSA Timéo",
        "BLANC PIERROT Léa",
        "BOUTIN Hugo",
        "BOYRIE Naïa",
        "CHAMBON Anthony",
        "CHOLLET Luka",
        "COLET Raphaël",
        "DUVAL Will",
        "EL BOURAQADI Mayssa",
        "ETCHEVERRY Enara",
        "FERNANDEZ Heloise",
        "FERNANDEZ Hugo",
        "GIULIANI Luca",
        "LE ROUX ETCHEGARAY Chloé",
        "LEBARBIER Jaya",
        "LOAH MERLIN Landon Milan",
        "LUPIET Leelou",
        "MENCAGLIA Noé",
        "NOTARY Gabin",
        "PAVILLA Jahdem",
        "PINLOU Inaya",
        "POCHELU Intza",
        "POURTAU Chloé",
        "QUANDALLE Aina",
        "QUERE Nino Damien Jean",
        "VILLENAVE Paul",
    ],
    "64": [ // 6e4
        "AHAMAM HANNI Marwa",
        "ASSOUMANI LEDEUN Laïna",
        "BAUCHET Gabrielle",
        "CHAILLET Alessio",
        "CORDOVES DELAI Diego",
        "DEDOUIT Enea",
        "DEPORCQ Emma",
        "DOSPITAL Théo",
        "DOYA Tony",
        "DRODE Zoé",
        "DUBOURDIEU Oihan",
        "DUPUY Rose",
        "EL OMRI Yassmine",
        "GENESTE-PEBORDE Enzo",
        "HUMBERT Maïana",
        "JEGO Raphael",
        "JOSSET BUZE Mia",
        "LEGARTO Mathieu",
        "MAZAIN Maëlia",
        "MONTEGUT Sohan",
        "NGWE DUPRAT Tracy",
        "PARIS Louison",
        "POUSSARD Jeanne",
        "RICHOUX Pablo",
        "RIGUET MIMIAGUE Lucas",
        "SALLABERRY-SUPERVIELE Eliott",
        "SAMIR FAKIR Zakariae",
        "VALIZELOS LAVIGNE Romane",
    ],
};
