// Listes des élèves par classe (clé = niveau + numéro, ex. "61" pour la 6e1).
// Utilisées pour proposer automatiquement les vendeurs dans le bon de commande.
// Source : exports CSV des classes 2026-2027 (seuls les noms sont repris, élèves sortis exclus).
const ELEVES = {
    "61": [ // 6e1
        "ANDRES Elaia",
        "BELASRI Marwa",
        "BONNETERRE Lucie",
        "BOUKREDIA Ilias",
        "CANTAU Xabi",
        "CHRISTY Anna",
        "DESTRIBATS Esteban",
        "ERGUY Nahia",
        "ETCHAMENDY Nahia",
        "FUMERY Lise",
        "GARCIA ALBIERO Ethan",
        "GEYS Eneko",
        "GUEDMA MATTIVI Neyla",
        "HARANGER Eneko",
        "HUBERT Charline",
        "JAUREGUY Amets",
        "LABOURDIQUE Célia",
        "LAGARDE Amaia",
        "LAHETJUZAN Eneko",
        "LARZABAL Lorea",
        "MICHOT Sarah",
        "MIRANDE Jade",
        "PALÉ RECHIK Lola",
        "VALDES Zoé",
        "WRIGHT Louise",
    ],
    "62": [ // 6e2
        "AMORENA Pablo",
        "BONNEFON Lea",
        "BORDES Taïna",
        "BRIERE Eva",
        "CADELO MONNIN Mila",
        "COELHO Eneko",
        "DUBLANC Xan",
        "ETCHART Chloé",
        "ETCHEPARE Antton",
        "ETCHEVERRY Charlie",
        "EYHERAMOUNHO Andoni",
        "FERREIRA CONDON Andréa",
        "FLORES Thomas",
        "GANJAYEVA Banu",
        "HODET Louka",
        "HOUILLON Alicia",
        "JANICKI Louis",
        "JOCOU LARRE Extebe",
        "LAGARDE Antton",
        "MARSAN Adèle",
        "MAZAIN Luka",
        "RAGUE Eneko",
        "RALITAVAO RAKOTAVA ZAHA Alexis",
        "SIMOES DENOUAL Angèle",
        "TARTARIN Camille",
        "TINTINGER Amaia",
        "VIDON Eden",
        "VILARO Jade",
    ],
    "63": [ // 6e3
        "ALLEZY Ludwig",
        "ARRIETA Victoire",
        "AYENSA Timéo",
        "BLANC PIERROT Léa",
        "BOUTIN Hugo",
        "BOYRIE Naïa",
        "CHAMBON Anthony",
        "CHOLLET Luka",
        "COLET Raphaël",
        "DUVAL Will",
        "EL BOURAQADI Mayssa",
        "ETCHEVERRY Enara",
        "FERNANDEZ Heloise",
        "FERNANDEZ Hugo",
        "GIULIANI Luca",
        "LE ROUX ETCHEGARAY Chloé",
        "LEBARBIER Jaya",
        "LOAH MERLIN Landon Milan",
        "LUPIET Leelou",
        "MENCAGLIA Noé",
        "NOTARY Gabin",
        "PAVILLA Jahdem",
        "PINLOU Inaya",
        "POCHELU Intza",
        "POURTAU Chloé",
        "QUANDALLE Aina",
        "QUERE Nino Damien Jean",
        "VILLENAVE Paul",
    ],
    "64": [ // 6e4
        "AHAMAM HANNI Marwa",
        "ASSOUMANI LEDEUN Laïna",
        "BAUCHET Gabrielle",
        "CHAILLET Alessio",
        "CORDOVES DELAI Diego",
        "DEDOUIT Enea",
        "DEPORCQ Emma",
        "DOSPITAL Théo",
        "DOYA Tony",
        "DRODE Zoé",
        "DUBOURDIEU Oihan",
        "DUPUY Rose",
        "EL OMRI Yassmine",
        "GENESTE-PEBORDE Enzo",
        "HUMBERT Maïana",
        "JEGO Raphael",
        "JOSSET BUZE Mia",
        "LEGARTO Mathieu",
        "MAZAIN Maëlia",
        "MONTEGUT Sohan",
        "NGWE DUPRAT Tracy",
        "PARIS Louison",
        "POUSSARD Jeanne",
        "RICHOUX Pablo",
        "RIGUET MIMIAGUE Lucas",
        "SALLABERRY-SUPERVIELE Eliott",
        "SAMIR FAKIR Zakariae",
        "VALIZELOS LAVIGNE Romane",
    ],
    "51": [ // 5e1
        "AMESTOY Maylis",
        "AMORENA Esteban",
        "BENAC SAYASITH Nahia",
        "BIDEGAIN Oihan",
        "CARDON Lily",
        "DACHAGUER Sara",
        "DURRUTY Imanol",
        "GARAINS Lola",
        "IRUBETAGOYENA Elaia",
        "LABARTHE HIRIART Maitane",
        "LABASTIE Manon",
        "LO VECCHIO CERESUELA Tiago",
        "MAILLARD Antton",
        "MAUREL Noé",
        "MENESCLOU Malonn",
        "MEZRAI Inaki",
        "MOHTADA NOISETTE Kaïs",
        "MORALES Mylene",
        "NEPOMUCENO DURO Gabriel",
        "SANSEBASTIEN Lya",
        "SELLES Joan",
        "SESE-PINAQUY Amory",
        "TIZNEL Lou-Anne",
        "TROUNDAY Tom",
        "VIEGAS NEPOMUCENO Alycia",
        "VILLALUENGA BUTHAUD Telmo",
    ],
    "52": [ // 5e2
        "AMORENA--SUHUBIETTE Mila",
        "AYCAGUER ETCHEPARE Mikel",
        "CAZALON Uhaina",
        "CHETRIT Lucas",
        "DAMESTOY Elena",
        "DIOT JIMENEZ Luca",
        "DUBLANC Lili",
        "DUPONT Elven",
        "DUPONT Maïwenn",
        "ERAÇARRET BIGEY Iban",
        "EWASSADJA Iban",
        "GUITARD Xana",
        "LEVAUD GOYENECHE Milian",
        "MARSAN Pierre",
        "MENDIONDO GUERRIER Antton",
        "MORTET Aaron",
        "OLÇOMENDY Andrea",
        "PIERROT Amélia",
        "PITARCH Arthur",
        "PLAQUEVENT Mathias",
        "RAOULT Eloïse",
        "SALA Mathias",
        "SARHY Oihana",
        "VEGA Hugo",
        "VERGARA FERNANDEZ Eneko",
    ],
    "53": [ // 5e3
        "BEBE VALDES Louanne",
        "BOS Tom",
        "CHAILLET Laya",
        "DRAPERI Marius",
        "DUMERCQ Louis",
        "FAVARD LISSALDE Eneko",
        "FERREIRA Alexis",
        "GAUCHOT FOUJANET Roxanne",
        "HARAN Marie-Charlotte",
        "LAFFITTE Zeian",
        "LAFON YANCI Louis",
        "LANDABOURE Kyliann",
        "LARAVINE Enzo",
        "LEMAIRE Louka",
        "MERCIER Elise",
        "MONTOLIEU Txomin",
        "MOUNISSENS Yaël",
        "MOURICHOU SAF Khléo",
        "PERONNY Manon",
        "PEYROT Aines",
        "REITHINGER ARCHIDOIT Maia",
        "SALABERRY Milan",
        "TEIXEIRA BISET Kenzo",
        "TELLECHEA Xan",
        "THILL Rose",
    ],
    "54": [ // 5e4
        "AGUERRE Ainez",
        "AGUERRE Enaut",
        "ARNOULT Elise",
        "ARZAC SUZANNE Nora",
        "CHAMPAGNAC Louis",
        "CORNU Ylan",
        "DA SILVA FRIAS Tiago",
        "DELACOUR Andréa",
        "DUHART ECHEVARRIA Naïa",
        "FELTEN Sacha",
        "GUEROULT Sacha",
        "JAVERNAUD Looane",
        "LABAT Jone",
        "LE GALLOU Noah",
        "LEROY Antonin",
        "MARTINON Maxime",
        "MASCARENHAS Gabin",
        "MELO MOREIRAS Tania",
        "MOISSANT Léandre",
        "MOYA ROBRECHT Gabriel",
        "OTTO NDOPELE Nathan",
        "PEREIRA Tobias",
        "PLUMAIN-SICARD Maël",
        "SERVELLE Elya",
        "TORRALBO HOLLEBECQ Enzo",
    ],
    "55": [ // 5e5
        "AVDOYAN David",
        "BAUD ARRIGNON Nolan",
        "BOTTEGA Margaux",
        "CAZENAVE Deyan",
        "COUTURIER Lylou",
        "DE CLERCK Mathys",
        "DUBOURDIEU Mattin",
        "ESPAGNACQ PEREZ Lenny",
        "FEVRE Gabriel",
        "FLEUREAU Salomé",
        "GARCIA Lola",
        "GIOVANNUCCI Massimo",
        "HEGO CAMUS Basile",
        "HIRABOURE Justine",
        "MARÉCHAL MAGALHAES Lilly",
        "MARTEAU LABBEZ Mathys",
        "MASSOL Mathis",
        "MATEOS Baptiste",
        "MONGUILLOT Justine",
        "MOUCHEBEUF Wayat",
        "MOUTOU-HELVADJIAN Maé",
        "PICOT Thibault",
        "RODRIGUES CARVALHO Miguel",
        "TEIXEIRA Rafael",
        "YUENG KWAI Maui",
    ],
    "41": [ // 4e1
        "ARBURUA Elorri",
        "ARCHIDOIT Lea",
        "BELLECAVE Mathilde",
        "BURGUBURU Camille",
        "CANTAU Pierre",
        "DU ROY DE CHAUMARAY Maggie",
        "DUBLANC Patxi",
        "DUMAS Elorri",
        "DUVIEU GARCIA Inaya",
        "ELISSALDE Andoni",
        "GAYOT Yohann",
        "GONÇALVES FERREIRA Sandro",
        "HAYET Pharell",
        "HEGUY Julen",
        "IRASSART Zoé",
        "LABARERE Thomas",
        "LAFITTE Enea",
        "LAGOURGUE Iban",
        "LARREA Katixa",
        "LISSARRAGUE Aines",
        "LOPEZ PALACIOS Antonin",
        "LUCAS Doric",
        "MALDA Elaia",
        "MORALES Elya",
        "OSPITAL Paul",
        "PENALBA Kenzo",
        "SENACQ-BODNAR Leia",
        "SUZANNE Lola",
        "SYLVESTRE Rodrigues",
        "URBIDE CHEMBERO Uxue",
    ],
    "42": [ // 4e2
        "BOSCQ Joane",
        "CHEMBERO Elea",
        "DARDINIER NEULAT Uhaina",
        "DE MIGUEL Mayi",
        "DUBREUIL Jayson",
        "DUBREUIL Ty",
        "DUHAU Manon",
        "EPELVA Emma",
        "ETCHAMENDY Andoni",
        "ETCHEBARNE Julia",
        "GULCKERS Lenka",
        "HARISMENDY Elena",
        "LARRABURU Lilia",
        "LARRAMENDY Léon",
        "LARREGAIN Amaiur",
        "LARZABAL Idoia",
        "LOUSTAUNAU Esteban",
        "MENCAGLIA Aymeric",
        "MIRAILH Benjamin",
        "MIRANDE Léa",
        "PAYET Noa",
        "QUEHEILLALT Eneko",
        "RAYNAUD LESTARPÉ Enzo",
        "SARHY Bixente",
        "SEIN--LANIEZ Maxence",
        "SUZANNE Lorea",
        "TESSIER Malo",
        "TRESPEUCH Izia",
        "VIDAL Manoa",
        "YECHE Robin",
    ],
    "43": [ // 4e3
        "ABRY Pierre",
        "ALBANDOS Elaia",
        "ALVES LUPÉRINI Shanna",
        "BAUD-ARRIGNON Liam",
        "BEAUCHET Elias",
        "BERTY Anaé",
        "BOUSQUET Leo",
        "CAYTAN DIXIT Alice",
        "DAMESTOY Haize",
        "DUHART Lilia",
        "DUHART Naia",
        "ERRECART CATHERINE Tiago",
        "FEREY Lindsay",
        "GARCIA CADET Emma",
        "HANUS Jean",
        "JOSSET BUZE Jordan",
        "LACOUARA SAINT-MARTIN Elsa",
        "LANGLERE Clément",
        "LE BELLEC Lisa",
        "LEON Sacha",
        "LESTAGE Yelena",
        "MARCOUD Léa",
        "MENDES FRANCE Amaïa",
        "MENDES FRANCE Ambre",
        "ONDARTS ELICAGARAY Mael",
        "POEYDESSUS Oihan",
        "RICHOUX Chloé",
        "SAPHORE LAPEYRE Iluna",
        "TORRES Lola",
        "VACHET Jon",
    ],
    "44": [ // 4e4
        "ARNOULT Justin",
        "AUDRAN Yoël",
        "AUROY Ambre",
        "CAZENAVE MARTIN Liam",
        "CONSTANTIEUX Elorri",
        "CUESTA PINEAU Maeva",
        "DANEY ETCHART Elaïa",
        "DESTRIBATS SAMBRONE Enzo",
        "DUPERRON Clément",
        "FARHAT EL OUAHAMI Rayane",
        "FERNANDES ALARD Lucas",
        "FERRADOU RUA Hoïan",
        "FERREIRA MARQUES Julia",
        "FORTIS Mathéo",
        "GOUAS RODRIGUES Jade",
        "GUINDO Aaliyah",
        "HAIGLER Tyrone",
        "LAFOURCADE Lorea",
        "LARREGAIN Julen",
        "LASSEGUETTE Aaron",
        "LOONIS CAMON Inès",
        "MARCOUX Jules",
        "MARGUERITTE Mayana",
        "MENCAGLIA Lucien",
        "MOLAND Inés",
        "OLIVAN Nathan",
        "ROBERT Anaïa",
        "ROBQUIN Baptiste",
        "SANGLA Romane",
    ],
    "31": [ // 3e1
        "ALBERDI Alexandre",
        "ALBERRO Iban",
        "AMORENA Enara",
        "AMORENA Nora",
        "ARCHI LECHHAB Sara",
        "ARRIJURIA-VENTURI Lyra",
        "BAUCHET Raphaël",
        "BELHOMME Jonah",
        "BETBEDER Lila",
        "CARN Andoni",
        "DUHART Allande",
        "ETCHEVERRY HAYET Mathieu",
        "EWASSADJA Clara",
        "EYHERAMOUNHO Maiana",
        "FAIZON Manon",
        "FERREIRA CONDON Elena",
        "GARAU REMETTER Max",
        "GRAVE Bastien",
        "GUEDMA MATTIVI Ayat",
        "HARAMBOURE Rafaël",
        "HARAN Antoine",
        "HOUSSET Lili",
        "MAUREL Lilou",
        "ROBQUIN Ines",
        "STROPPA Ryuunosuke",
    ],
    "32": [ // 3e2
        "AHAMAM Safaa",
        "BERRIDI Louis",
        "CAMY Jeanne",
        "CARON LEVESQUE Dean",
        "DACHAGUER Nahia",
        "ERRECA Hugo",
        "ETCHEBARNE CHEMBERO Ana",
        "ETCHEBARNE CLAVERIE Fanny",
        "ETCHEGOYEN Mattin",
        "FOURNIER Jules",
        "GRATADOUR Nael",
        "GRUEL ANDUEZA Nahia",
        "GULIYEV Aytaj",
        "JAUREGUY Aines",
        "LASSALLE Idoïa",
        "LASSERRE Léo",
        "MONGUILLOT Louis",
        "NENON BERNARD Tiziana",
        "OILLATAGUERRE Intza",
        "OXARANGO Mattin",
        "PIRON Émilie",
        "POISSON Enéa",
        "RAYNAUD LESTARPÉ Dimitri",
        "RECARTE Elaia",
        "SAMIR FAKIR Khadija",
    ],
    "33": [ // 3e3
        "AGUERRE Leire",
        "ANORGA Lina",
        "ANTONIO Aaron",
        "BAUDUIN Eloïse",
        "BOULARD Laura",
        "CABALLERO Esteban",
        "DARRIEUMERLOU Maika",
        "DUPUY VIGNERON Claire",
        "GELAK Nathan",
        "GENESTE-PÉBORDE Lucas",
        "GONZALEZ Nahia",
        "GUITARD Milan",
        "ISTILLART Maitena",
        "LEJEUNE Thalia",
        "MAUREL Louanne",
        "MAZAIN Amaia",
        "MAZAIN Eneko",
        "MENDIONDO Simon",
        "NOBLANC Lorenzo",
        "OLAIZOLA Mattin",
        "RESTOUX Oyan",
        "ROBIN Elliot",
        "RONDOT Ihintza",
        "RUBIO DE TERAN Elsa",
        "RUSSEIL Lilou",
        "SAINT-JEAN Xan",
        "TOUYA Célia",
    ],
    "34": [ // 3e4
        "AL HANDIRAH Chamseddine",
        "ARANAZ Maia",
        "DE CASTRO LOPES Phileas",
        "DERSION Nohan",
        "DUCHESNE HONTAS Sam",
        "FABRE Romy",
        "FERREIRA MEIRA Luana",
        "FLORES Mareva",
        "FRAILLON Lorianne",
        "GONÇALVES DA FONTE Mathis",
        "LABARTHE Fabien",
        "LABORDE FUENTES Jon",
        "LAGARDE Xan",
        "LE CHENADEC Eloane",
        "LOISELET Julia",
        "LORENZINI Fabio",
        "MASCARENHAS Elliot",
        "MENETRIER KHIAR Cassandre",
        "MIQUEL Louise",
        "PERRIER-MELMI Nolan",
        "PONCELET Paul",
        "REBELO FERNANDES Ana",
        "REITHINGER-ARCHIDOIT Louis",
        "RENTIEN Maëlys",
        "TASSET Lucie",
        "TOUSSAINT Lenny",
    ],
};
